version: "3.8"

services:
  whisper:
    container_name: whisper
    image: paidax/faster-whisper:0.0.4
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: always
    ports:
      - 7650:7650
    command: uvicorn main:app --port 7650 --host 0.0.0.0
